import React from 'react';
import { Collection, CollectionItem, Row, Col } from 'react-materialize';

const ActionPotential = () => {
  return (
    <div>
      <Row>
        <Col m={2}/>
        <Col s={12} m={8} className='container'>
          <Col s={12} m={8} className='grid-example'>
            <h2>The Action Potential</h2>
            <Col s={12} m={10} className='grid-example'>
              <Collection header='Key Points'>
                <CollectionItem>Show how that action potential relates to the ECG waveform</CollectionItem>
                <CollectionItem>Sequential deplolarization and repolarization</CollectionItem>
                <CollectionItem>QRS and T wave morphology</CollectionItem>
                <CollectionItem>Voltage gradients</CollectionItem>
                <CollectionItem>Isoelectric segments</CollectionItem>
              </Collection>
            </Col>
          </Col>
        </Col>
        <Col m={2} />
      </Row>
      <Row>
        <Col m={2} />
        <Col s={12} m={8} className='grid-example'>
          <p>It is helpful to have an understanding of the factors responsible for the electrocardiographic wave form in order to understand the normal electrocardiogram and to interpret the changes in the wave form caused by  diseases and drugs. </p>
          <h3>Events at cellular level</h3>
          <video className='card-media' width="auto" height="500" autoplay loop controls>
            <source src="https://www.understandingecg.org/sites/default/files/media/ecg_images/5_electrolyte/5_1_v.mp4" type="video/mp4" />
              Your browser does not support the video tag.
          </video>
          <p>The cell membrane is a lipid bilayer in which there are multiple channels, or pores made of different proteins, through which ions flow, both into and out of the cell, generating the trans-membrane action potential.  After a cell is stimulated, the first ion to cross the cell membrane is sodium which has a concentration of about 140 mmol in the extracellular space and about 4 mmol inside the cell. It flows rapidly into the cell causing its depolarization and generating the upstroke of the trans-membrane action potential. Then calcium ions begin to flow slowly into the cell and potassium ions, which have an intracellular concentration of about 130 mmol and an extracellular concentration of about 4 mmol begin to leave the cell.  These two ionic currents, which are flowing in opposite directions (calcium into the cell and potassium out of the cell), balance one another resulting in a flat portion of the action potential, referred to as the action potential the plateau, during which there is neither depolarization nor repolarization. Then, the flow of potassium ions out of the cell increases rather dramatically, causing the rapid repolarization of the trans-membrane action potential, returning it to its resting level.</p>
          <video className='card-media' width="auto" height="500" autoplay loop controls>
            <source src="https://www.understandingecg.org/sites/default/files/media/c1-6image1.ogg" type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          <p>If you were to do the experiment in which you record an electrocardiogram from an open chested animal or from a patient in the operating room and, at the same time, recorded the electrical activity of a single ventricular myocardial cell of the beating heart, you would get something similar to that shown in this figure in which the electrical activity from an individual ventricular cell is displayed above the simultaneously recorded electrocardiogram. As each cardiac cell is stimulated, it generates an action potential which is comprised of a phase of very rapid depolarization, the upstroke of the action potential, a plateau phase during which there is very slow repolarization, a phase of rapid repolarization and a resting phase.</p>
          <img src="https://www.understandingecg.org/sites/default/files/media/2-5-0.png" alt="t-wave generation"  className='card-media' height="400"/>
          <p>The electrocardiographic waveform reflects the electrical events occurring in the individual cells. The QRS complex of the electrocardiogram reflects the voltage gradients created by the sequential depolarization of all the ventricular cells and correlates to the rapid upstroke of the action potentials. In this figure the action potentials from 2 individual cells is shown. The first, is recorded from a cell near the apex of the heart and the second, from a cell near the base. The onset of the QRS occurs when the first cells in the sequence of depolarization are depolarized and the end of the QRS occurs when the last cells in the sequence are depolarized.
            {/* (show similar figure but with 2 action potentials and appropriate portions highlighted).  */}
            Similarly, the T wave reflects the voltage gradients created as the cells sequentially repolarize. The onset of the T wave occurs when the first cells to rapidly repolarize cells begin their phase of rapid repolarization, the apex of the T wave occurs when the initially repolarizing cells complete their repolarization and the end of the T wave occurs when the last cells to repolarize complete their repolarization.</p>
          <p>The ST segment reflects the plateau phase of the action potentials and the TP segment reflects the interval when all the cells are in their resting phase. {/*(same figure (1.7.9) */}. Under normal conditions, the transmembrane potentials of all the ventricular cells are at roughly the same level during the plateau and the same is true during the resting phase. As a result, there are no voltage gradients created during either of these phases even though the plateau and resting phases of the individual action potentials are at different transmembrane potential levels. It is for this reason that the ST and TP segments of the normal body surface electrocardiogram are at the same level (i.e. are iso-electric). {/*(show fig rom 2.4.3 but add 2nd AP as in 2.5.0).(will have to find appropriate figure(s))*/}</p>
          <p>However, deviation the TP segment or the ST segment will each appear as a deviation of the ST segment only because the TP segment is automatically centered by the ECG machine. Thus, depression of the TP segment will appear as ST segment elevation and elevation of the TP segment will appear as ST segment depression. If the TP segment and the ST segment move in the same direction and by the same amount, The TP and ST segments will remain isoelectric and the ECG will appear normal. In this graphic,{/*(show 2.4.2)*/} the red line represents the normal baseline.</p>
          <p>Changes in the duration of the total action potential caused by changes in the duration of the plateau or of the phase of rapid repolarization will cause changes in the interval from the onset of depolarization to the end of repolarization. This will be reflected on the electrocardiogram by changes in the duration of the QT interval. {/*(Show figure with appropriate changes in plateau and QT durations)*/}</p>
          <p>Slowing of the action potential upstroke without a changes in the sequence of depolarization,  and the resulting widening of the QRS complex is  most often caused by (or occurs with) an elevation in serum potassium, hypothermia and some antiarrhythmic drugs. Changes in the sequence of depolarization with the resulting change in both the shape and duration of the QRS complex is caused most often by inter and intra-ventricular conduction disturbances such as the bundle branch blocks.</p>
          <p>Changes in QRS amplitude  can be caused by a variety of factors including, but not limited to, the age, sex, race, and body build of the individual, by chamber hypertrophy and dilatation and by fluid in the pericardial and/or pleural spaces. </p>
          <p>Elevation of the ST segment is most often the result of acute myocardial ischemia or pericarditis, while ST segment depression can be caused by variety of factors. These include, but again, are not limited to ischemia, drugs, left ventricular hypertrophy and electrolyte abnormalities, particularly low serum potassium. </p>
          <p>T wave changes can be caused by many factors. Some are functional and benign, such as hyperventilation and changes in position, some are secondary to prolongation or changes in the sequence of depolarization and do not indicate an abnormality in repolarization, and some do indicate an abnormality in repolarization as caused by drugs and electrolyte abnormalities and by ischemia and hypertrophy. As such, T wave abnormities are, in my experience, the most common ECG abnormalities and the most difficult to diagnose correctly. </p>
          <p>The duration of the QT interval, like the duration of the action potential is rate dependent, It lengthens at  slow rates and shortens at rapid rates. For this reason, several correction formulae have been proposed to account for these rate effects and one or more of these are automatically applied by the digital ECG machines now in routine use to provide a (rate) corrected QT interval designated on the ECG print-out as QTc. In addition to rate, the QT interval is affected by QRS duration,  temperature,  drugs and electrolytes, ischemia and autonomic “tone”.  {/*  ( I don’t know how best to illustrate this section-  maybe a series of tables or bullet points to g with each paragraph, or maybe nothing)*/}</p>
          <p>Elevation of the ST segment is most often the result of acute myocardial ischemia or pericarditis, while ST segment depression can be caused by variety of factors. These include, but again, are not limited to ischemia, drugs, left ventricular hypertrophy and electrolyte abnormalities, particularly low serum potassium. </p>
          <p> T wave changes can be caused by many factors. Some are functional and benign, such as hyperventilation and changes in position, some are secondary to prolongation or changes in the sequence of depolarization and do not indicate an abnormality in repolarization, and some do indicate an abnormality in repolarization as caused by drugs and electrolyte abnormalities and by ischemia and hypertrophy. As such, T wave abnormities are, in my experience, the most common ECG abnormalities and the most difficult to diagnose correctly.</p>
          <p>Changes in the ST segment, T and U waves (repolarization changes). {/* III-17 (show 5.1.0)*/} A bit of basic science will help with an understanding of the changes in the repolarization that occur in a wide variety of clinical settings and are expressed electrocardiographically as changes in the ST segment, the T and U waves and the QT interval. The figure shown here represents the cell membrane and shows the ions that flow into and out of the cell and the electrical signal generated, the trans-membrane action potential, as the cell depolarizes and then repolarizes.</p>
          <p>{/* III-18 (Show1.50 and 1.7.9 side by side -is it possible to make one of the action potentials in dashed rather than solid line?)*/} This figure on the left shows the relationship between the sequence of depolarization and the QRS complex and the  figure on the right illustrates the relationship between ventricular action potentials recorded from 2 different locations in the normal beating heart to the simultaneously recorded ECG (shown without the P wave and PR interval). The first action potential is recorded from the IV septum. The second is recorded close to the right ventricular outflow tract. These represent the regions depolarized earliest and latest in the sequence of ventricular depolarization. </p>
          <p>When all the cells are in their resting state, during electrical diastole – shown in purple, they are at the same resting potential (of about -85 mV), and the TQ segment on the ECG, that is the segment between the end of the T wave and the onset of the following QRS complex, also shown in purple, is a flat straight line. The onset of the QRS complex corresponds to the upstroke of the first cells in the sequence of depolarization to be activated. The end of the QRS complex corresponds to the upstroke of the last cells in the sequence of depolarization. Thus, the QRS complex is generated by (or represents) the voltage gradients created as the ventricular cells are sequentially depolarized. </p>
          <p>The ST segment of the ECG, shown in yellow/green corresponds to the plateau phase of the action potentials, also shown in yellow/green. You will note that the St segment is at the same place on the ECG paper as the TQ segment (i.e.is iso-electric with the TQ segment), even though the plateau of the trans-membrane action potential is at abut 0mV while the resting trans-membrane potential, as noted above, is at about -85mV.  The reason for this apparent discrepancy is the following:   When the cells are in the plateau phase, their trans-membrane potentials will be at the same level (approximately  0mV) and there will no voltage gradients. Since there are no voltage gradients there will be no current flow, and no deviation of the body surface ECG waveform from its baseline. The important thing to remember is this:</p>
          <p>IT IS THE VOLTAGE GRADIENTS THAT ARE CREATED AS THE CELLS SEQUENTIALLY DEPOLARIZE AND THEN SEQUENTIALLY REPOLARIZE THAT ARE RESPONSIBLE FOR THE WAVEFORM RECORDED ON THE BODY SURFACE ELECTROCARIOGRAM.</p>
          <p>If there are voltage gradients during either the plateau phase of the action potential, the ST segment will deviate from the isoelectric baseline resulting in ST segment elevation or depression.  This is the reason for the ST segment changes associated with hypertrophy, electrolyte abnormalities, drugs, pericarditis and ischemia.{/*III-19 (show 2.5.0)*/} The T wave on the body surface electrocardiogram reflects voltage gradients created as the ventricular cells sequentially repolarize, just as the QRS complex reflects those created as the cells sequentially depolarize.</p>
        </Col>
        <Col m={2} />
      </Row>
    </div>
  );
}

export default ActionPotential;